name: Build and Deploy of Static Site

on:
  push:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Mkdocs Setup
        run: pip install mkdocs

      - name: Mkdocs Build
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote add target https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/asap-programmer/static-site.git
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push target main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    

     


