name: Build and Deploy of Static Site

on:
  push:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Mkdocs Setup
        run: pip install mkdocs

      - name: Mkdocs Build
        run: mkdocs build

      - name: Deploy 🚀
        uses: asap-programmer/static-site@v4
        with:
          branch: test/v4
          folder: .
          clean: false
          single-commit: true

    

     


